### PR TITLE
Address some rust-clippy issues.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by Hoverbear** [comment]
Re-running test.

**Comment by frewsxcv** [comment]
Rebased

**Comment by Hoverbear** [comment]
Shoot, this was my fault. I'll fix it, sorry about that.

**Comment by frewsxcv** [comment]
Rebased.

**Comment by Hoverbear** [comment]
@frewsxcv You're so fast. Thanks so much for rebasing **twice**, what a hero!

**Comment by Hoverbear** [comment]
@homu r+

**Pull request merged**
